### ISSUE TITLE
Error opening the project

### ISSUE THREAD

**Issue by noncom** [Unity-Technologies/SmallOfficeRayTracing#2]
I have some questions and errors on opening this project:

1. The project seems to target Unity 2019.3b2 instead of the currently latest 2019.3.b6 since it matches with the b2 installation automatically and when trying to open it with b6 it presents the do-you-want-to-upgrade-the-project-to-the-latest-Unity-version dialog. Is this intended? Why does it not target version b6?

2. The installation steps from readme don't work. Upon opening the project I get: 

![image](https://user-images.githubusercontent.com/2920144/66311634-92ec7380-e917-11e9-957e-9a4fe4e2df27.png)

Which is true, there are no such files neither in the release zip, nor upon cloning the repository. Unity Editor fails to work with this project, opening it with 2019.3b2 gives compilation errors that prevent it from entering the play mode, and upgrading and opening it with 2019.3b6 fails to even display the scene.

Please advise.

**Comment by cybertheme** [comment]
After upgrading to 2019.3b6 You can find scenes in Assets/3D Scene. Drag it to the hierarchy and unload or remove other scene. You have two tiers 

Tier 1 | Balances performance with quality. Use this tier for games and other high-frame rate applications.
-- | --
Tier 2 | A ray tracing implementation that is significantly more resource-intensive than Tier 1. This allows for effects with higher image quality. Use this tier for automotive, production, or graphics demos.

![unity_dxr_scene](https://user-images.githubusercontent.com/48512266/66361897-74957080-e935-11e9-83dd-c8ff61a2b695.jpg)

EDIT: 
1. Ok, do not use releases rar folder, instead use git-lfs. In rar release in manifest there is reference to local packages that have specific folder structure. You do not have these packages. Be sure to pull all LFS files.
![image](https://user-images.githubusercontent.com/48512266/66366615-dc53b780-e945-11e9-9a2c-64ad68499d90.png)

2. Then convert to unity 2019.3b6 project.
3. Transfer scene to the hierarchy.
4. Hit play

**Comment by sebastienlagarde** [comment]
Hi, those issue should be fix. And yes, think to use git-lfs to clone the projects.

>The project seems to target Unity 2019.3b2 instead of the currently latest 2019.3.b6 since it matches >with the b2 installation automatically and when trying to open it with b6 it presents the do-you->want-to-upgrade-the-project-to-the-latest-Unity-version dialog. Is this intended? Why does it not >target version b6?

We don't upgrade the project all the time, we only update it time to time during the beta version, then we will update it for the official release.

**Comment by noncom** [comment]
I see. I **could not** make this project work with either LFS-enabled Git or downloading the release. I had to manually pull the Scriptable Render Pipeline repo into the "SRP" directory inside the project. Only this fixed the errors. 

This idea **only** came to me after I saw it in this project: https://github.com/alelievr/HDRP-Custom-Passes since I could not have guessed that this step was required to be done manually, and that nothing that README says about launching the project actually helps launching the project. In my exprience the current directions in the README are incorrect and misleading. Also, there is no reference for the SRP repo within this project, so no matter if you are using LFS-enabled Git or not, the reference is simply not there. Or I'm totally missing something.

I still think that the process can be somehow be made easier or at least documented properly. Are you sure that you can clone this project to a totally new folder and still have everything pulled in correctly?

**Comment by AnthonyPaulO** [comment]
Can confirm that method described by Cybertheme works, just a slight tweak I've added:
Download the rar file and extract it.
Go to packages folder and edit manifest.json, replacing all local paths with "7.1.2"; save.
Open project, then drag/drop either tier 1 or tier2 scene to Hierarchy (as shown in his screenshot) and run.
Ignore console errors, works for me.

**Comment by noncom** [comment]
¯\\_(ツ)_/¯ well must be I'm doing something wrong, this well may be the case. Okay, if it works for people, I think this case can be closed for now.

**Comment by merttoka** [comment]
`Unity 2019.3.0f6_27ab2135bccf` [also `2019.3.2f1_c46a3a38511e` and `2019.3.4f1_4f139db2fdbd`] crashes when loading the project. When I look into `error.log` The first error is as follows:
```
nvwgf2umx.dll caused an Access Violation (0xc0000005)
  in module nvwgf2umx.dll at 0033:a270bb50.
```

I downloaded the files using git-lfs and loaded the project as-is. Do I somehow need to change the `manifest.json` file? I am also using the latest Nvidia drivers (442.50) for my RTX 2080 Max-Q.

**Comment by sebastienlagarde** [comment]
There is know problem with 2019.3.0f6, please use 2019.3.2f1 to not crash, thanks and sorry for the inconvenience

**Comment by merttoka** [comment]
> There is know problem with 2019.3.0f6, please use 2019.3.2f1 to not crash, thanks and sorry for the inconvenience

`2019.3.0f6`, `2019.3.2f1`, and `2019.3.4f1` are all crashing with the same error. I see Unity editor briefly, and then the Unity crash window immediately after. 

**EDIT:**
It looks like a driver issue. @sebastienlagarde, which Nvidia driver version you can run the project with?

**Comment by sebastienlagarde** [comment]
Currently work with 441.87 nvidia driver version

**Comment by vkaramian** [comment]
Project crashes on 2019.3.4.1 does not open!

**Comment by sebastienlagarde** [comment]
>Project crashes on 2019.3.4.1
Sadly DXR is broekn in 2019.3.4.1, please use 2019.2f1.  or 2019.3.6f1 when available.
That"s say it isn't related to the crash, do you have a callstack?

Many crash that we are seeing are due to incorrect driver version.

**Comment by merttoka** [comment]
I also tried it with 2029.2, which Nvidia driver version are you using?

**Comment by sebastienlagarde** [comment]
> 2029.2

This version isn't supported. Raytracing have been added in 19.3

Right now the official combination is 2019.3.2f1  + Branch 2019.3 of this repository + HDRP 7.2..1 + Currently work with 441.87 nvidia driver version

**Comment by vkaramian** [comment]
> > Project crashes on 2019.3.4.1
> > Sadly DXR is broekn in 2019.3.4.1, please use 2019.2f1.  or 2019.3.6f1 when available.
> > That"s say it isn't related to the crash, do you have a callstack?
> 
> Many crash that we are seeing are due to incorrect driver version.

thanks @sebastienlagarde what version of the Nvidia Driver are you using? Also does the team plan on making the upgrade to the new version of Unity Editor, assuming 2019.3.6.f.1

**Comment by vkaramian** [comment]
> > 2029.2
> 
> This version isn't supported. Raytracing have been added in 19.3
> 
> Right now the official combination is 2019.3.2f1 + Branch 2019.3 of this repository + HDRP 7.2..1 + Currently work with 441.87 nvidia driver version

Spend the past hour and used the recommended settings, including downgrading the Nvidia driver. Still same issue. A note here, the version on the 2019.3 branch is 2019.3.1f1. I also assume, we don't need to upgrade to the new Asset Manager package. 

Was able to do custom Ray Tracing, but not through the engine pipeline.

**Comment by vkaramian** [comment]
Ok, I see 2019.3.6 is out today. Will be trying it with the new Editor, I hope it will be fixed!
